name: Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run test

      - name: check new
        uses: patriknyblad/add-pr-checks@v1.0.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          checks-path: 'sample-checks/*'
