name: Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npx vite build


      - name: check new
        uses: patriknyblad/add-pr-checks@v1.0.0
        with:
          # Your Github API token. Recommended to use as a secret ${{ secrets.GITHUB_TOKEN }} 
          token: ${{ secrets.GH_TOKEN }} 

          # The path to where you are generating all the checks YAML/JSON files in your build, this supports glob patterns.
          checks-path: 'sample-checks/*'

          # A YAML document with an array of checks you want to add to the PR directly from your workflow.
          checks: |
            - name: Estimated App Size
              value: 116MB
              summary: |
                # Estimated app download size
              text: |
                This size is just and estimation and is the result of **compressing** the build output and measuring the 
                size. It should be fairly close to the size reported on the store.
            - name: App download QR code
              value: See details
              summary: |
                ![QR-Code](https://example.com/qr-code)

      
    
